### ISSUE TITLE
Support Gandi API version 5 keys

### ISSUE THREAD

**Issue by robdollard** [mandatoryprogrammer/TrustTrees#10]
Gandi switched to API version 5, it's impossible to get the key of the latest version for new users, and the new one does not fit.

![dec992b174c71e1ab8c1170c064fd868](https://user-images.githubusercontent.com/40629638/48754252-d532a500-ecb2-11e8-92da-8ac7d4f919e5.png)

**Comment by davidnewhall** [comment]
It appears new users cannot make v4 keys.

**Comment by KevinHock** [comment]
Okay I fixed this in [version v2.0.0](https://github.com/mandatoryprogrammer/TrustTrees/blob/master/CHANGELOG.md#v200), thanks all! 

(The `--domain-check` option has been replaced with `--gandi-api-v4-key`/`--gandi-api-v5-key`)
