### ISSUE TITLE
Upload images to S3 with TrustTrees

### ISSUE THREAD

**Issue by KevinHock** [mandatoryprogrammer/TrustTrees#22]
We can already pass AWS credentials to TrustTrees

Let's make it so that we can pass a bucket and prefix, then upload the e.g. `png`s to an S3 bucket. In case you made e.g. Jira tickets with the alerts, and wanted to link an S3 signed URL or something, to make the graph easily viewable outside of the box TrustTrees is running on.

Make sure to doc in the readme that you need `PutObject` etc.

**Comment by tanx16** [comment]
(We can close this now)

**Comment by KevinHock** [comment]
++, thanks for the pointer, I’m used to GithHub auto-closing.
