### ISSUE TITLE
 error: unrecognized arguments: --resolvers

### ISSUE THREAD

**Issue by masti10** [mandatoryprogrammer/TrustTrees#30]
trusttrees.py --target example.com --open --resolvers
usage: trusttrees.py [-h] (-t TARGET_HOSTNAME | -l TARGET_HOSTNAMES_LIST) [-o]
                     [--gandi-api-v4-key GANDI_API_V4_KEY]
                     [--gandi-api-v5-key GANDI_API_V5_KEY] [-x EXPORT_FORMATS]
trusttrees.py: error: unrecognized arguments: --resolvers

**Comment by KevinHock** [comment]
Okay this should be fixed. 👍
Sorry about that, I had forgotten to update the PyPI version.

https://pypi.org/project/TrustTrees/ has the latest, it works on Python 3.

Also after `pip install`ing it will be at e.g. `trusttrees -h`
