### ISSUE TITLE
ModuleNotFoundError: No module named 'trusttrees'

### ISSUE THREAD

**Issue by Popyllol** [mandatoryprogrammer/TrustTrees#32]
Environment:
$ lsb_release -a
LSB Version:    core-11.0.1ubuntu1-noarch:security-11.0.1ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
$ python3 -V
Python 3.7.5

I tried it as user in ~/.local/...:
$ pip3 install --user trusttrees

I tried it as root in /usr/local:
# pip3 install trusttrees

I tried it from git as root:
# git clone https://github.com/mandatoryprogrammer/TrustTrees
# cd TrustTrees
# pip3 install .

I always get:
# trusttrees 
Traceback (most recent call last):
  File "/usr/local/bin/trusttrees", line 6, in <module>
    from trusttrees.__main__ import main
ModuleNotFoundError: No module named 'trusttrees'

Any hints for a python dummy?
Thanks!
   Lars

**Comment by dgzlopes** [comment]
Commenting here, as I think It's closely related to this issue.

I got the same `ModuleNotFoundError` the first time I tried to install TrustTrees:
```
$ pyenv local 3.7.0
$ pip install trusttrees
...
$ trusttrees
Traceback (most recent call last):
  File "/home/dgzlopes/.pyenv/versions/3.7.0/bin/trusttrees", line 5, in <module>
    from trusttrees.__main__ import main
ModuleNotFoundError: No module named 'trusttrees'
```
With the same OS as in #33. 

I ended installing it with ```git clone``` and ```pip install -e .``` and got it working :)

**Comment by KevinHock** [comment]
Thanks @dgzlopes 👍

**Comment by KevinHock** [comment]
Fixed, thank you everyone!
