### ISSUE TITLE
Add DNSimple integration

### ISSUE THREAD

**Issue by dgzlopes** [mandatoryprogrammer/TrustTrees#36]
It could be interesting to add support for `checking-domains` using [DNSimple](https://dnsimple.com/).

They have a REST API and clients on multiple languages (Python one is on [development stage](https://github.com/dnsimple/dnsimple-python)).

e.g API usage:
```
# Check for domain availability

curl -H "Authorization: Bearer [TOKEN]" \ 
-H "Accepts: application/json" \ 
https://api.sandbox.dnsimple.com/v2/[ACCOUNT_ID]/registrar/domains/[DOMAIN_NAME]/check
```

disclaimer: happy customer :stuck_out_tongue:

**Comment by dgzlopes** [comment]
Wow, this was **ultra quick**! Thank you a lot @tanx16 :pray:

And @KevinHock, for the review :P

Closing.

**Comment by KevinHock** [comment]
👍🏼  Would you like me to bump a new version, @dgzlopes?

**Comment by dgzlopes** [comment]
Sure!

**Comment by KevinHock** [comment]
Done 👍🏼
