### ISSUE TITLE
Repeating hostname in ns_query?

### ISSUE THREAD

**Issue by cclauss** [mandatoryprogrammer/TrustTrees#5]
https://github.com/mandatoryprogrammer/TrustTrees/blob/master/trusttrees.py#L140

```python
>>> hostname = 'my_host'
>>> hostname
'my_host'
>>> hostname += hostname + "."
>>> hostname
'my_hostmy_host.'
```

**Comment by mandatoryprogrammer** [comment]
Fixed in this diff: https://github.com/mandatoryprogrammer/TrustTrees/commit/0665877ad160c7a8b606dcd7100c59800d6e2986

Stupid mistake :) thanks for filing the issue!
